server:
  port: 8083

spring:
  banner:
    location: classpath:banner.txt
  data:
    mongodb:
      uri: mongodb://localhost:27017/coursesdb #connection to mongo db
  application:
    name: business-invoices-v1
  kafka:
    bootstrap-servers: localhost:9092 #kafka server
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: latest
      properties:
        specific:
          avro:
            reader: true
        schema.registry.url: http://0.0.0.0:8081
  schema-registry:
    url: http://0.0.0.0:8081 #Schema registry server

logging:
  level:
    io:
      confluent:
        kafka:
          serializers: debug

